version: "3.8"

services:
  dbpostgres:
    image: postgres:14.5
    container_name: dbpostgres
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
      - ./.docker/pg_init_scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=passworddb
      - PGDATA=/var/lib/postgresql/data/pgdata
    network_mode: bridge
  # nodejs:
  #   build:
  #     context: .
  #     dockerfile: .docker/Dockerfile
  #   image: nodejsimg
  #   container_name: nodejs
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - PORT=3000
  #     - DB_CONFIG=postgres://postgres:passworddb@dbpostgres:5432/postgres
  #   network_mode: bridge
  #   links:
  #     - dbpostgres
  #   depends_on:
  #     dbpostgres:
  #       condition: service_started
volumes:
  pgdata:
