version: "3.8"

services:
  dbpostgres:
    image: postgres:14.5
    container_name: dbpostgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
      - ./.docker/pg_init_scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=passworddb
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - ntwbridge
  # nodejs:
  #   build:
  #     context: .
  #     dockerfile: .docker/Dockerfile
  #   image: nodejsimg
  #   container_name: nodejs
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - PORT=3000
  #     - ENVIRONMENT=DEV
  #     - DB_CONFIG=postgres://postgres:passworddb@dbpostgres:5432/postgres
  #   depends_on:
  #     dbpostgres:
  #       condition: service_started
  #   networks:
  #     - ntwbridge
networks:
  ntwbridge:
    driver: bridge
volumes:
  pgdata:
